// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb_5-Sbetumu9OQ28ueQ5mwltMAQ8dIKA',
    appId: '1:817978465446:web:e26db19af0cff110c2e867',
    messagingSenderId: '817978465446',
    projectId: 'brujula-9cd97',
    authDomain: 'brujula-9cd97.firebaseapp.com',
    storageBucket: 'brujula-9cd97.appspot.com',
    measurementId: 'G-T65NL19HZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjoYpau5eUtu7VCXBoYguLSWA-Ho5lsT8',
    appId: '1:817978465446:android:58aea95dc030764fc2e867',
    messagingSenderId: '817978465446',
    projectId: 'brujula-9cd97',
    storageBucket: 'brujula-9cd97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA4PwfeeUzA97GgAFgoSsPwboGqkQttNY',
    appId: '1:817978465446:ios:b685f244dd8b36e4c2e867',
    messagingSenderId: '817978465446',
    projectId: 'brujula-9cd97',
    storageBucket: 'brujula-9cd97.appspot.com',
    iosBundleId: 'com.example.brujulaEmocional',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA4PwfeeUzA97GgAFgoSsPwboGqkQttNY',
    appId: '1:817978465446:ios:19ea71f128e25552c2e867',
    messagingSenderId: '817978465446',
    projectId: 'brujula-9cd97',
    storageBucket: 'brujula-9cd97.appspot.com',
    iosBundleId: 'com.example.brujulaEmocional.RunnerTests',
  );
}
